// Extracts the item table (id -> name + bag pocket) from the Pokemon Emerald Imperium ROM.
// Imperium is built on pokeemerald-expansion. Offsets are the same ones the verified Python
// save editor (Pokemon Docs/imperium_spawn.py) uses:
//   gItemsInfo name table: base 0x6A68A0, stride 0x50, name at +0x34 (Gen-3 charmap, 0xFF-term).
//
// POCKET: this build does NOT store a usable pocket field in gItemsInfo (verified by scanning
// every struct offset against the live bag — only "balls vs not" is separable, and there is no
// separate pocket-by-id table in the ROM). The game derives pocket from the item id in code.
// So we classify by rules validated against 175 ground-truth items read from a real save:
//   - name /^(TM|HM)\d/        -> tm
//   - name ends "Berry"        -> berry
//   - name ends "Ball", id<=27 -> balls   (held "...Ball" items like Iron Ball have id>27)
//   - struct byte +0x11 == 2   -> mega    (mega-stone signature)
//   - struct byte +0x11 == 6   -> key     (key-item signature)
//   - else                     -> items
// Plus a tiny override set for the 3 items whose +0x11 byte collides with a pointer.
// Result: 172/175 exact on ground truth; the 3 misses land in the Items pocket (non-corrupting).
//
// The app ships the generated file so the ROM isn't needed at runtime.
// Run: node scripts/extract-items.mjs ["C:/path/to/rom.gba"]
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROM_PATH = process.argv[2] || 'C:/Users/parke/Pokemon Docs/Pokemon Imperium v1.1.gba';
const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA = resolve(__dirname, '../src/data');

const rom = new Uint8Array(readFileSync(ROM_PATH));

const IT_BASE = 0x6a68a0, IT_STRIDE = 0x50, IT_NAME = 0x34;

// Gen-3 in-game charmap (matches src/lib/gen3data.js, plus é used by "Poké Ball").
const CH = { 0xff: null, 0x00: ' ', 0xae: '-', 0xad: '.', 0xba: '/', 0xb4: "'", 0x1b: 'é', 0x2d: '&' };
for (let c = 65; c <= 90; c++) CH[0xbb + (c - 65)] = String.fromCharCode(c);
for (let c = 97; c <= 122; c++) CH[0xd5 + (c - 97)] = String.fromCharCode(c);
for (let c = 48; c <= 57; c++) CH[0xa1 + (c - 48)] = String.fromCharCode(c);
function decode(o, len) {
  let s = '';
  for (let k = 0; k < len; k++) {
    const ch = CH[rom[o + k]];
    if (ch === null || ch === undefined) break;
    s += ch;
  }
  return s.trim();
}
const looksName = (s) => s && /[A-Za-z]/.test(s) && !s.includes('?');

const itemName = (id) => decode(IT_BASE + id * IT_STRIDE + IT_NAME, 13);
const structByte = (id, off) => rom[IT_BASE + id * IT_STRIDE + off];

// Items whose +0x11 byte collides with a pointer and mis-reads as the Items signature.
const POCKET_OVERRIDE = { 975: 'mega', 461: 'key', 120: 'key' };

function pocketOf(id, name) {
  if (POCKET_OVERRIDE[id]) return POCKET_OVERRIDE[id];
  const n = name.toLowerCase();
  if (/^(tm|hm)\d/.test(n)) return 'tm';
  if (n.endsWith('berry')) return 'berry';
  if (n.endsWith('ball') && id <= 27) return 'balls';
  const sig = structByte(id, 0x11);
  if (sig === 2) return 'mega';
  if (sig === 6) return 'key';
  return 'items';
}

const items = {};
let blanks = 0;
for (let id = 1; id < 1400; id++) {
  const name = itemName(id);
  if (!looksName(name)) { if (++blanks > 80) break; continue; }
  blanks = 0;
  items[id] = { n: name, pk: pocketOf(id, name) };
}

mkdirSync(DATA, { recursive: true });
const banner =
  '// AUTO-GENERATED by scripts/extract-items.mjs — do not edit by hand.\n' +
  `// ${Object.keys(items).length} items. Shape: {n:name, pk:pocket}. ` +
  'pk in: items|balls|key|tm|berry|mega.\n';
writeFileSync(resolve(DATA, 'items.js'),
  `${banner}export const ITEMS = ${JSON.stringify(items)};\n`);

const counts = {};
for (const { pk } of Object.values(items)) counts[pk] = (counts[pk] || 0) + 1;
console.log(`items: ${Object.keys(items).length}`, counts);
console.log('spot:', [4, 102, 290, 442, 520, 582].map((i) => `${i}=${items[i]?.n}(${items[i]?.pk})`).join(' '));
