// Extracts species names + base stats from the Pokemon Emerald Imperium ROM and writes
// src/data/species.js. Imperium is built on pokeemerald-expansion, which stores everything in a
// gSpeciesInfo[] struct array (260 bytes/entry). Located empirically:
//   gSpeciesInfo[0] (SPECIES_NONE placeholder) at 0xD42658, stride 260.
//   base stats (HP,Atk,Def,Spe,SpA,SpD as u8) at struct offset 0; species name at offset 44.
// The app ships the generated file so the ROM isn't needed at runtime.
//
// Run: node scripts/extract-species.mjs ["C:/path/to/rom.gba"]
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROM_PATH = process.argv[2] || 'C:/Users/parke/Pokemon Docs/Pokemon Imperium v1.1.gba';
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, '../src/data/species.js');

const ARRAY0 = 0xd42658, STRIDE = 260, NAME_OFF = 44, NAME_LEN = 12;

const M = { 0xff: null, 0x00: ' ', 0xae: '-', 0x2e: '.', 0xb4: "'", 0xba: '/' };
for (let c = 65; c <= 90; c++) M[0xbb + (c - 65)] = String.fromCharCode(c); // A-Z
for (let c = 97; c <= 122; c++) M[0xd5 + (c - 97)] = String.fromCharCode(c); // a-z
for (let c = 48; c <= 57; c++) M[0xa1 + (c - 48)] = String.fromCharCode(c); // 0-9

const rom = new Uint8Array(readFileSync(ROM_PATH));

function decodeName(id) {
  const o = ARRAY0 + id * STRIDE + NAME_OFF;
  let s = '';
  for (let k = 0; k < NAME_LEN; k++) {
    const ch = M[rom[o + k]];
    if (ch === null || ch === undefined) break; // 0xFF terminator / unknown
    s += ch;
  }
  return s.trim();
}
const statsOf = (id) => {
  const o = ARRAY0 + id * STRIDE;
  return [rom[o], rom[o + 1], rom[o + 2], rom[o + 3], rom[o + 4], rom[o + 5]]; // HP,Atk,Def,Spe,SpA,SpD
};

const species = {};
let blanks = 0;
for (let id = 1; id < 2200; id++) {
  const name = decodeName(id);
  if (!name || name.includes('?') || !/[A-Za-z]/.test(name)) {
    if (++blanks > 60) break; // ran off the end of the table
    continue;
  }
  blanks = 0;
  species[id] = { n: name, s: statsOf(id) };
}

const count = Object.keys(species).length;
const banner = `// AUTO-GENERATED by scripts/extract-species.mjs — do not edit by hand.\n` +
  `// ${count} species extracted from the Imperium ROM. Stats order: [HP, Atk, Def, Spe, SpA, SpD].\n`;
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `${banner}export const SPECIES = ${JSON.stringify(species)};\n`);
console.log(`Wrote ${count} species to ${OUT}`);
console.log('Spot check:', [1, 642, 784, 1378].map((i) => `${i}=${species[i]?.n}`).join('  '));
